try{
//something 
}catch(error){
    throw new error ('comethingwent wrong ',{cause :error });

}